---
title: "R Notebook"
output: html_notebook
---

```{r}
library(WikidataR)
library(rtoot)

```

# Récupération des toots de Plazi 

```{r authentication on Mastodon and identification of Plazi Mastodon account}
library(rtoot)
auth_setup() # authentification de l'utilisateur
# documentation on Rtoot is available here https://www.rdocumentation.org/packages/rtoot/versions/0.3.4
id <- search_accounts("plazi_species")
print(id)
```

```{r collection of PLazi\'s toots}
df <- get_account_statuses("109284766172512524", limit = 400L)
head(df$content, 1)
```


```{r récupération espèce}
library(stringr)
library(dplyr)
pattern <- "(?<=</p><p>)(.*?)(?=</p><p>)"
df <- df %>%
  mutate(species_name = str_extract(content, pattern))  
#str_to_sentence(country_discovery$country_of_discovery)
head(df, 10)
```



items problématiques : 
https://mastodon.green/@plazi_species/113917317111853431
https://mastodon.green/@plazi_species/113916252425285117


```{r exclusion espèces végétales }
library(stringr)
library(dplyr)

df <- df %>%
  filter(!str_detect(species_name, 'Treatment:'))
head(df, 10)

```






```{r html tags deletion in toot content }
library(purrr)
library(rvest)
df$content <- map_chr(df$content, function(x) {
  tryCatch({
    read_html(x) %>% html_text()
  }, error = function(e) {
    # renvoie le message original si une erreur est rencontrée
    return(x)
  })
})
head(df$content, 10)
```
```{r récupération DOIs}
library(stringr)
pattern <- "(?<=doi.org/)(.*?)(?=#)"
df <- df %>%
  mutate(doi = str_extract(content, pattern))  
#str_to_sentence(country_discovery$country_of_discovery)
head(df, 10)
```


```{r récupération pays de découverte}
library(stringr)
pattern <- "(?<=from #)(\\w+)"
df <- df %>%
  mutate(
    country_of_discovery = str_extract(content, pattern),
    country_of_discovery = str_to_title(country_of_discovery) 
  )
head(df, 10)
```

```{r sélectionner les colonnes importantes pour nous }
df <- select(df, species_name, country_of_discovery, doi)
head(df,10)
```

# Propriétés : 

location of discovery : [P189](https://www.wikidata.org/wiki/Property:P189)
described by source : [P1343](https://www.wikidata.org/wiki/Property:P1343)





```{r get the list of all countries in english with their qid}
library(WikidataR)
library(WikidataQueryServiceR)
library(dplyr)
# URL to this query on Wikidata query service
countries_qid <- query_wikidata('
SELECT ?item ?itemLabel 
WHERE
{

     ?item wdt:P31 wd:Q6256 .
           
              SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}')
qid_no_url <- gsub('[http://www.wikidata.org/entity/]', '', countries_qid$item) # extrait le qid de la colonne item et ajoute une colonne au tableau des pays
countries_qid <- as.data.frame(countries_qid) # fait de countries_qid2 un dataframe afin que mutate puisse fonctionner (ligne suivante)
countries_qid <- countries_qid %>% 
  mutate(
    qid=qid_no_url,
    country_of_discovery = paste(countries_qid$itemLabel)
    )
        
head(countries_qid, 10)
```

```{r jonction des deux tableau }

df1 <- merge(df, countries_qid, by = "country_of_discovery")
df1 <- select(df1, species_name, qid, country_of_discovery, doi)
head(df1, 10)

```

```{r récupération des items qui existent déjà dans Wikidata}

get_qid <- function(name) {
  results <- find_item(name)  # Search for the name in Wikidata
  if (length(results) > 0) {
    return(results[[1]]$id)  # Extract QID of the first result
  } else {
    return(NA)  # Return NA if no result is found
  }
}
df1$QID_items <- sapply(df1$species_name, get_qid)
head(df1, 10)



```

```{r récupération des items qui ne sont pas présents dans Wikidata}
#df2 : items à créer dans Wikdata
df2  <- df1[is.na(df1$QID_items),] # filter(df1 =="NA") won't do it (see here https://stackoverflow.com/questions/7980622/subset-of-rows-containing-na-missing-values-in-a-chosen-column-of-a-data-frame#7980765)
head(df2, 10)

```

```{r récupération des items qui ne sont déjà présents dans Wikidata}
#df3 : items déjà créésdans Wikdata
df3  <- df1[!is.na(df1$QID_items),] # filter(df1 =="NA") won't do it (see here https://stackoverflow.com/questions/7980622/subset-of-rows-containing-na-missing-values-in-a-chosen-column-of-a-data-frame#7980765)
head(df3, 10)

```


# création d'un tableau à partir des données relatives aux éléments à créer

```{r selection des trois items de tête de la liste df2)}

df2_sub <- slice_head(df2, n = 3, by = NULL)
df2_sub <- df2_sub %>% 
  mutate(
    row_num = row_number(),
    item = paste0("CREATE_",row_num),
    Len = paste0(df2_sub$species_name),
    P189 = paste0(df2_sub$qid),
    P356 = paste0(df2_sub$doi),
  )
df2_sub <- select(df2_sub, item, species_name, Len, P189, P356)
print(df2_sub)

```

```{r code de Katharina Brunner}
library(tidyr)
library(stringr)

import <- df2_sub %>% 
  select(item, 
         matches("^L", ignore.case = FALSE), 
         matches("^D", ignore.case = FALSE), 
         # if there are some Sitelinks to other Wiki pages
         #matches("^S", ignore.case = FALSE), 
         matches("^P", ignore.case = FALSE)) %>% 
  pivot_longer(cols = 2:last_col(), names_to = "property", values_to = "value") %>% 
  # fix helper with two columns referring to the same property
  mutate(property = str_remove(property, "_.*")) %>% 
  filter(!is.na(value)) %>% 
  distinct()

print(import)
```


```{r envoyer vers wikidata }
library(WikidataR)
write_wikidata(
  items        = import$item,
  properties   = import$property,
  values       = import$value,
  format       = "api",
  api.username = "Udo_Bolano", 
  api.token    = "$2y$10$qy3Omn7Dn4DaXAD1QBWcs.dNjrKwlrc.cFX2rVZMyQ7oYt2xYSmJS", #REDACTED#
  )

```




api.token    = mettre ici le token récupéré sur https://quickstatements.toolforge.org/#/user

voir mode d'emploi ici : https://katharinabrunner.de/2022/06/wikibase-wikidata-etl-data-import-with-r/ 